### ISSUE TITLE
This theme is super lovely 

### ISSUE THREAD

**Issue by enzime4u** [adanperez/nada-theme#2]
Hi there, i like this theme very very much !
so... congratulations ....

can you also make an iterm theme and also add some bg color variants ( like more contrast , dark navy ) ???

those are just suggestions ! 

great work

**Comment by adanperez** [comment]
Thanks!  Next time I update this I will look into making some variants and iTerm.  

You can currently customize this how you want though.
In your VSCode settings file, add the following section if you don't already have it:

```json
...
"workbench.colorCustomizations": {
    "[Nada]": {
      "editor.background": "#191c2c" 
    }
  },
...
```

There you can override any colors you want for my theme.
More info here: https://code.visualstudio.com/docs/getstarted/themes#_workbench-colors

**Comment by enzime4u** [comment]
Yep, thank you for the support , also please work on it , it is a super good looking theme !
